<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>booklastli</name>
   <tag></tag>
   <elementGuidId>55a0e0d5-3414-4929-b67a-b788c8431277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li[last()]</value>
      <webElementGuid>6c7c0f89-e102-486e-bbc5-73bbe63cccc5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
